spring:
  mvc:
    view:
      suffix: .html
      prefix: /
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:greetingDb;DB_CLOSE_DELAY=-1
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        ddl-auto: create-drop
        
        
management:
  endpoints:
    web:
      exposure:
        include: '*'
        
defaultgreeting: "Welcome to IBM MS BOOTCAMP"